"""
Central configuration.

This module is *pure data*: importing it reads no files and has no side effects.
Everything that defines a run — paths, the dataset registry, the solver settings,
the ``BacktestConfig`` and the batch grid — lives here, so the scripts
(``backtest.py``, ``analyze.py``, ``datagen.py``) share one source of truth.
"""
from __future__ import annotations

import os
from dataclasses import dataclass

# =============================================================================
# Paths
# =============================================================================

DATA_DIR       = "DATA"
EMPIRICAL_DIR  = f"{DATA_DIR}/Empirical"
# NOTE: the folder name is the historical "Artifical" typo on purpose — the
# generated data already lives there; renaming would only risk breaking it.
ARTIFICIAL_DIR = f"{DATA_DIR}/Artifical"

RESULTS_DIR = "Ergebnisse"
SUMMARY_DIR = f"{RESULTS_DIR}/Zusammenfassung"

# Dataset registry:  name -> (csv path, date format)
DATASETS = {
    "TRBC":  (f"{EMPIRICAL_DIR}/TRBC_Business_Sectors_clean.csv", "%Y-%m-%d"),
    "SP500": (f"{EMPIRICAL_DIR}/S&P500_Adj.csv",                  "%d.%m.%y"),
    "Dow":   (f"{EMPIRICAL_DIR}/Dow_Adj.csv",                     "%Y-%m-%d"),
    # synthetic price series generated by datagen.py
    "MonteCarlo": (f"{ARTIFICIAL_DIR}/monte_carlo.csv", "%Y-%m-%d"),
    "GARCH_sim":  (f"{ARTIFICIAL_DIR}/garch.csv",       "%Y-%m-%d"),
    "DCC_sim":    (f"{ARTIFICIAL_DIR}/dcc.csv",         "%Y-%m-%d"),
}


# Fed Funds total-return series: a daily index *level* (starts at 100), columns
# "Exchange Date";"Close". The loaders take its pct_change -> daily simple
# risk-free return, so a freshly downloaded export must keep this name/format.
RISK_FREE_FILE = f"{EMPIRICAL_DIR}/FED_FUNDS.csv"


def risk_free_file() -> str:
    """Path to the Fed Funds total-return CSV (the risk-free series)."""
    if not os.path.exists(RISK_FREE_FILE):
        raise FileNotFoundError(
            f"Risk-free file not found: {RISK_FREE_FILE} "
            "(Fed Funds total-return index, exported as 'Exchange Date';'Close')."
        )
    return RISK_FREE_FILE


# =============================================================================
# Solver configuration (riskfolio-lib / cvxpy)
# =============================================================================
# cvxpy's default C++ canonicalisation backend aborts (a hard SIGABRT) with
# numpy 2.x in this environment; the SciPy backend is correct and stable. We
# route every riskfolio solve through it. This is harmless on a healthy install
# and required on a broken one.
SOLVERS = ["CLARABEL"]
SOL_PARAMS = {"CLARABEL": {"canon_backend": "SCIPY"}}


# =============================================================================
# Backtest configuration
# =============================================================================

@dataclass(frozen=True)
class BacktestConfig:
    """Everything that defines a single backtest run."""

    dataset: str = "DCC_sim"
    train_window: int = 4 * 252          # ~4 years of trading days
    prediction_window: int = 1           # test/forecast horizon in days
    garch_p: int = 1
    garch_q: int = 1
    cov_methods: tuple[str, ...] = ("Historical", "GARCH", "DCC")
    models: tuple[str, ...] = ("MVP", "HRP", "ERC")
    log_weights: bool = True             # also dump per-window weights to weights.csv
    max_workers: int = 3

    @property
    def garch_tag(self) -> str:
        return "" if (self.garch_p, self.garch_q) == (1, 1) else f"_g{self.garch_p}-{self.garch_q}"

    @property
    def output_dir(self) -> str:
        return f"{RESULTS_DIR}/{self.dataset}/{self.train_window}_{self.prediction_window}{self.garch_tag}"


# =============================================================================
# Batch grid  (backtest.py runs every (dataset, train, pred) combination below)
# =============================================================================
# Full grid: every training window (252-day steps, ~1..10 years) x prediction horizon.
GRID_TRAIN = [252 * i for i in range(1, 11)]   # 252, 504, ..., 2520
GRID_PRED  = [1, 5, 10, 21]

# (train_window, prediction_window) combinations per dataset. A single run is just
# a one-entry COMBOS (e.g. {"DCC_sim": [(1008, 1)]}).
COMBOS = {
    "DCC_sim":    [(1008, 1)],  # just one combo for the synthetic DCC data
    "GARCH_sim":  [(1008, 1)],  # just one combo for the synthetic GARCH data
    "MonteCarlo": [(1008, 1)],  # just one combo for the synthetic Monte Carlo data
    "TRBC": [(train, pred) for train in GRID_TRAIN for pred in GRID_PRED],
}
