"""
Main entry point: choose the datasets and window sizes in the settings block
below, then run

    python main.py

This file also holds the shared configuration (paths, dataset registry, solver
settings) that backtest.py, analyze.py and datagen.py import.
"""

# =============================================================================
# Settings
# =============================================================================
# Every dataset in RUN_DATASETS is backtested over every combination of
# training window and prediction window (in trading days, 252 = one year).

RUN_DATASETS  = ["TRBC"]                      # keys of DATASETS below, e.g. ["TRBC", "Dow", "SP500"]
TRAIN_WINDOWS = [1008, 1260, 1512, 1764, 2016, 2268, 2520, 252, 504, 756]  # 252, 504, ..., 2520 trading days
PRED_WINDOWS  = [1, 5, 10, 21]                # forecast horizon(s) in days
MAX_WORKERS   = 6             # number of parallel worker processes

# Which covariance estimators and portfolio models to compare
COV_METHODS = ["Historical", "GARCH", "DCC"]
MODELS      = ["MVP", "HRP", "ERC"]

# Order of the univariate GARCH(p, q) volatility models
GARCH_P = 1
GARCH_Q = 1

LOG_WEIGHTS = True  # also save the portfolio weights of every window to weights.csv


# =============================================================================
# Paths
# =============================================================================

DATA_DIR       = "DATA"
EMPIRICAL_DIR  = f"{DATA_DIR}/Empirical"
ARTIFICIAL_DIR = f"{DATA_DIR}/Artifical"  # folder name keeps the old typo on purpose

RESULTS_DIR = "Ergebnisse"
SUMMARY_DIR = f"{RESULTS_DIR}/Zusammenfassung"

# Dataset registry: name -> (csv path, date format)
DATASETS = {
    "TRBC":  (f"{EMPIRICAL_DIR}/TRBC_Business_Sectors_clean.csv", "%Y-%m-%d"),
    "SP500": (f"{EMPIRICAL_DIR}/S&P500_Adj.csv",                  "%d.%m.%y"),
    "Dow":   (f"{EMPIRICAL_DIR}/Dow_Adj.csv",                     "%Y-%m-%d"),
    # synthetic price series generated by datagen.py
    "MonteCarlo": (f"{ARTIFICIAL_DIR}/monte_carlo.csv", "%Y-%m-%d"),
    "GARCH_sim":  (f"{ARTIFICIAL_DIR}/garch.csv",       "%Y-%m-%d"),
    "DCC_sim":    (f"{ARTIFICIAL_DIR}/dcc.csv",         "%Y-%m-%d"),
}

# Fed Funds total-return index: a daily index level starting at 100, with the
# columns "Exchange Date";"Close". Its percentage change is used as the daily
# simple risk-free return, so a freshly downloaded export must keep this format.
RISK_FREE_FILE = f"{EMPIRICAL_DIR}/FED_FUNDS.csv"


# =============================================================================
# Solver settings (riskfolio-lib / cvxpy)
# =============================================================================
# cvxpy's default C++ backend crashes with numpy 2.x on this machine, the SciPy
# backend works fine, so every riskfolio optimization is routed through it.

SOLVERS    = ["CLARABEL"]
SOL_PARAMS = {"CLARABEL": {"canon_backend": "SCIPY"}}


"""
Builds the output folder name for one run, e.g. Ergebnisse/Dow/1008_1.
The GARCH order is only appended when it is not the default (1, 1).
"""
def output_dir(dataset, train_window, prediction_window):
    garch_tag = "" if (GARCH_P, GARCH_Q) == (1, 1) else f"_g{GARCH_P}-{GARCH_Q}"
    return f"{RESULTS_DIR}/{dataset}/{train_window}_{prediction_window}{garch_tag}"


# =============================================================================
# Running the full grid
# =============================================================================

if __name__ == "__main__":
    # imported here because backtest.py itself imports the settings from this file
    import backtest

    for dataset in RUN_DATASETS:
        prices, log_returns, rf = backtest.load_dataset(dataset)
        for train_window in TRAIN_WINDOWS:
            for prediction_window in PRED_WINDOWS:
                print(f"\n=== {dataset} {train_window}_{prediction_window} ===", flush=True)
                backtest.run_backtest(dataset, log_returns, rf, train_window, prediction_window)
