"""
Rolling-window portfolio backtest.

We compare three portfolio construction methods (MVP, HRP, ERC) using three
covariance estimators (historical sample covariance, GARCH with constant
correlation, and DCC-GARCH with dynamic correlation), plus a naive 1/N
benchmark.

Returns are LOG returns for the modelling part (GARCH/DCC like additive,
well-behaved returns). For evaluation and plotting we convert back to SIMPLE
returns, because a portfolio return is a weighted sum of *simple* asset returns,
not of log returns.
"""
import os
from concurrent.futures import ProcessPoolExecutor

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from util import (
    calculate_summary_metrics,
    cov_constant_correlation,
    cov_dcc,
    estimate_cov_matrix_historical,
    fit_garch_univariate,
    get_erc_weights,
    get_hrp_weights,
    get_mvp_weights,
)

# --- Configuration -----------------------------------------------------------

DATASETS = {  # name: (filepath, date_format)
    "TRBC":  ("DATA/Empirical/TRBC_Business_Sectors_clean.csv", "%Y-%m-%d"),
    "SP500": ("DATA/Empirical/S&P500_Adj.csv",                  "%d.%m.%y"),
    # artificial price series generated by artificial_data.py
    "MonteCarlo": ("DATA/Artifical/monte_carlo.csv", "%Y-%m-%d"),
    "GARCH_sim":  ("DATA/Artifical/garch.csv",       "%Y-%m-%d"),
    "DCC_sim":    ("DATA/Artifical/dcc.csv",         "%Y-%m-%d"),
}

MAX_WORKERS       = 3
DATASET           = "DCC_sim"
TRAIN_WINDOW      = int(4 * 252)
PREDICTION_WINDOW = 1
RISK_FREE_FILE    = "DATA/Empirical/Price History_20260611_1835.csv"  # Fed Funds total-return index
GARCH_P           = 1
GARCH_Q           = 1
COV_METHODS       = ["Historical", "GARCH", "DCC"]    # covariance estimators to run
MODELS            = ["MVP", "HRP", "ERC"]             # portfolio construction methods
LOG_WEIGHTS       = True                              # also dump per-window weights to weights.csv

_GARCH_TAG  = "" if (GARCH_P, GARCH_Q) == (1, 1) else f"_g{GARCH_P}-{GARCH_Q}"
_OUTPUT_DIR = f"Ergebnisse/{DATASET}/{TRAIN_WINDOW}_{PREDICTION_WINDOW}{_GARCH_TAG}"

# --- Load data ---------------------------------------------------------------

filepath, date_format = DATASETS[DATASET]
prices = pd.read_csv(filepath, index_col=0)
prices.index = pd.to_datetime(prices.index, format=date_format, errors="coerce")
prices = prices[prices.index.notna()]
prices = prices.loc[prices.notna().sum(axis=1) >= int(0.5 * prices.shape[1])]

# log returns for modelling:  r_t = ln(P_t / P_{t-1})
log_returns = np.log(prices / prices.shift(1)).iloc[1:]

# drop assets that are flat (zero return) more than half the time
zero_frac = (log_returns == 0).sum() / log_returns.notna().sum()
log_returns = log_returns.loc[:, zero_frac < 0.5]


def load_risk_free(price_index):
    """
    Daily risk-free return from the Fed Funds total-return index, aligned to the
    given price dates.

    The metrics work on SIMPLE returns, so the risk-free is the SIMPLE daily
    return of the index level (I_t / I_{t-1} - 1).  We align the index *level* to
    the price dates first and then take the percentage change, so the risk-free
    accrual covers exactly the same day spacing as the portfolio returns.
    """
    rf = pd.read_csv(RISK_FREE_FILE, sep=";", decimal=",", encoding="utf-8-sig")
    dates = rf["Exchange Date"]
    for de, en in {"Mär": "Mar", "Mai": "May", "Okt": "Oct", "Dez": "Dec"}.items():
        dates = dates.str.replace(de, en, regex=False)  # German -> English months
    level = pd.Series(rf["Close"].values, index=pd.to_datetime(dates, format="%d-%b-%Y"))
    level = level.sort_index().reindex(price_index).ffill()
    return level.pct_change()


rf_daily = load_risk_free(prices.index)


# --- Small dispatch helper ---------------------------------------------------

def get_weights(model, cov):
    if model == "MVP":
        return get_mvp_weights(cov)
    if model == "HRP":
        return get_hrp_weights(cov)
    if model == "ERC":
        return get_erc_weights(cov)
    raise ValueError(f"unknown model: {model}")


# --- Rolling backtest --------------------------------------------------------

def process_window(start):
    """Run one rolling window. Returns (per_period_returns, records, dates)."""
    train = log_returns.iloc[start : start + TRAIN_WINDOW]
    test  = log_returns.iloc[start + TRAIN_WINDOW : start + TRAIN_WINDOW + PREDICTION_WINDOW]

    # Universe is decided from TRAINING information only (no look-ahead into the
    # test window): assets with >=90% observations in the window and a valid
    # observation on the last training day (i.e. tradeable at formation time).
    train = train.loc[:, train.notna().mean() >= 0.9]
    train = train.loc[:, train.iloc[-1].notna()]
    if train.shape[1] == 0 or test.empty:
        return {}, [], [], {}, None

    # same universe in the test window; a missing test return means the asset did
    # not trade that day, so its return is 0 (we don't drop it after the fact).
    test = test[train.columns]
    test_simple = (np.exp(test) - 1).fillna(0.0)

    # build the requested covariance matrices; fit GARCH only once and reuse it
    cov_by_method = {}
    if "Historical" in COV_METHODS:
        cov_by_method["Historical"] = estimate_cov_matrix_historical(train)
    if "GARCH" in COV_METHODS or "DCC" in COV_METHODS:
        variances, std_resid = fit_garch_univariate(train, PREDICTION_WINDOW, GARCH_P, GARCH_Q)
        if "GARCH" in COV_METHODS:
            cov_by_method["GARCH"] = cov_constant_correlation(train, variances)
        if "DCC" in COV_METHODS:
            cov_by_method["DCC"] = cov_dcc(variances, std_resid)

    # historical cov is also used for the naive portfolio's forecast std
    cov_hist_full = cov_by_method.get("Historical")
    if cov_hist_full is None:
        cov_hist_full = estimate_cov_matrix_historical(train)

    # list of (model, cov_type, weights, cov) to evaluate
    naive_w = pd.Series(1.0 / train.shape[1], index=train.columns)
    jobs = [("Naive", "N/A", naive_w, cov_hist_full)]
    for method, cov in cov_by_method.items():
        if cov is None or cov.shape[1] == 0:
            continue
        for model in MODELS:
            jobs.append((model, method, get_weights(model, cov), cov))

    per_period = {}
    records = []
    weights_info = {}                       # name -> (target weights, drifted end weights)
    formation_date = test.index[0]          # rebalance date for this window
    for model, cov_type, weights, cov in jobs:
        name = "Naive" if model == "Naive" else f"{model} {cov_type}"
        cols = list(weights.index)
        port_returns = test_simple[cols] @ weights
        per_period[name] = port_returns.values.tolist()

        # drifted end-of-window weights (for turnover): each asset's start weight
        # grows with its gross return over the holding window, then renormalise.
        gross = (1.0 + test_simple[cols]).prod(axis=0)
        end_val = weights * gross
        end_weights = end_val / end_val.sum()
        weights_info[name] = (weights, end_weights)

        w = weights.values
        forecasted_std = float(np.sqrt(w @ cov.loc[cols, cols].values @ w))
        records.append({
            "Model": model,
            "Covariance Type": cov_type,
            "Window Index": start // PREDICTION_WINDOW,
            "Mean Return": port_returns.mean(),
            "Forecasted Std": forecasted_std,
        })
    return per_period, records, list(test.index), weights_info, formation_date


def main():
    starts = list(range(0, len(log_returns) - TRAIN_WINDOW - PREDICTION_WINDOW + 1, PREDICTION_WINDOW))
    total = len(starts)

    results = {}          # name -> list of simple period returns
    records = []
    period_dates = []
    weights_hist = {}     # name -> list of (formation_date, target weights) in window order
    end_hist = {}         # name -> list of drifted end-of-window weights (same order)
    with ProcessPoolExecutor(max_workers=MAX_WORKERS) as executor:
        for i, (per_period, recs, dates, winfo, fdate) in enumerate(executor.map(process_window, starts), start=1):
            records.extend(recs)
            period_dates.extend(dates)
            for name, rets in per_period.items():
                results.setdefault(name, []).extend(rets)
            for name, (target_w, end_w) in winfo.items():
                weights_hist.setdefault(name, []).append((fdate, target_w))
                end_hist.setdefault(name, []).append(end_w)
            print(f"\r{i}/{total} windows completed", end="", flush=True)
    print()

    if not records:
        print("No valid rolling windows (train window longer than the data?).")
        return

    os.makedirs(_OUTPUT_DIR, exist_ok=True)
    metrics = pd.DataFrame(records)
    metrics.to_csv(f"{_OUTPUT_DIR}/backtest_metrics.csv", index=False)

    # per-period returns per model (rows = dates), so any subset can be replotted later
    if period_dates:
        returns_df = pd.DataFrame(results, index=pd.to_datetime(period_dates))
        returns_df.index.name = "Date"
        returns_df.to_csv(f"{_OUTPUT_DIR}/returns.csv")

    # average turnover per strategy: at each rebalance, how much weight is traded
    # to go from the previous window's drifted weights to the new target weights
    # (sum of absolute weight changes = buys + sells, aligned over the union of
    # both windows' universes).
    avg_turnover = {}
    for name, hist in weights_hist.items():
        ends = end_hist[name]
        per_window = []
        for k in range(1, len(hist)):
            prev_end, target = ends[k - 1], hist[k][1]
            idx = prev_end.index.union(target.index)
            per_window.append(float(np.abs(target.reindex(idx).fillna(0.0)
                                            - prev_end.reindex(idx).fillna(0.0)).sum()))
        avg_turnover[name] = float(np.mean(per_window)) if per_window else np.nan

    # optional: per-window target weights in long format (Date, strategy, asset, weight)
    if LOG_WEIGHTS:
        weight_rows = []
        for name, hist in weights_hist.items():
            model, cov_type = ("Naive", "N/A") if name == "Naive" else name.rsplit(" ", 1)
            for fdate, target_w in hist:
                for asset, wt in target_w.items():
                    weight_rows.append({"Date": fdate, "Model": model,
                                        "Covariance Type": cov_type,
                                        "Asset": asset, "Weight": wt})
        pd.DataFrame(weight_rows).to_csv(f"{_OUTPUT_DIR}/weights.csv", index=False)

    # --- summary -------------------------------------------------------------

    # average forecast (annualised) std per model/cov type
    avg_fcst = metrics.groupby(["Model", "Covariance Type"])["Forecasted Std"].mean() * np.sqrt(252)

    # daily risk-free return aligned to the evaluated dates (same order as results)
    rf_aligned = rf_daily.reindex(pd.to_datetime(period_dates)).fillna(0.0).values

    summary_rows = []
    for name, rets in results.items():
        rets = np.array(rets)
        if rets.size == 0:
            continue
        model, cov_type = ("Naive", "N/A") if name == "Naive" else name.rsplit(" ", 1)
        row = calculate_summary_metrics(rets, rf_aligned)
        fcst = avg_fcst.get((model, cov_type), np.nan)
        row["Model"] = model
        row["Covariance Type"] = cov_type
        row["Ann. Std (fcst)"] = fcst
        row["Real / Fcst Std"] = row["Ann. Std"] / fcst if fcst and fcst > 0 else np.nan
        row["Avg Turnover"] = avg_turnover.get(name, np.nan)
        summary_rows.append(row)

    col_order = ["Model", "Covariance Type", "Ann. Return", "Ann. Std", "Ann. Std (fcst)",
                 "Real / Fcst Std", "Avg Turnover", "Ann. Sharpe", "Ann. Sortino", "Max Drawdown",
                 "Calmar Ratio", "CVaR (95%)", "Skewness", "Excess Kurtosis"]
    summary = pd.DataFrame(summary_rows).sort_values(["Model", "Covariance Type"])[col_order]
    summary.to_csv(f"{_OUTPUT_DIR}/summary.csv", index=False)
    print("Annualized performance summary:")
    print(summary.to_string(index=False))

    # --- plot ----------------------------------------------------------------

    if not any(results.values()):
        print("No valid rolling windows to plot.")
        return

    x_axis = pd.to_datetime(period_dates)
    fig, ax = plt.subplots(figsize=(12, 6))
    for name, rets in results.items():
        ax.plot(x_axis, 100 * np.cumprod(1 + np.array(rets)), label=name)
    ax.set_title("Portfolio Value Starting at 100")
    ax.set_xlabel("Date")
    ax.set_ylabel("Portfolio Value")
    ax.legend()
    ax.grid(True)
    fig.autofmt_xdate()
    fig.tight_layout()
    plt.savefig(f"{_OUTPUT_DIR}/Simulation.png")


if __name__ == "__main__":
    main()
