"""
Central configuration.

This module is *pure data*: importing it reads no files and has no side effects.
Everything that used to be a scattered module-level constant or a mutated global
now lives here, either as a plain constant or on the ``BacktestConfig`` dataclass
that the backtest takes as its single source of truth.
"""
from __future__ import annotations

import glob
from dataclasses import dataclass

# =============================================================================
# Paths
# =============================================================================

DATA_DIR       = "DATA"
EMPIRICAL_DIR  = f"{DATA_DIR}/Empirical"
# NOTE: the folder name is the historical "Artifical" typo on purpose — the
# generated data already lives there; renaming would only risk breaking it.
ARTIFICIAL_DIR = f"{DATA_DIR}/Artifical"

RESULTS_DIR = "Ergebnisse"
SUMMARY_DIR = f"{RESULTS_DIR}/Zusammenfassung"

# Dataset registry:  name -> (csv path, date format)
DATASETS = {
    "TRBC":  (f"{EMPIRICAL_DIR}/TRBC_Business_Sectors_clean.csv", "%Y-%m-%d"),
    "SP500": (f"{EMPIRICAL_DIR}/S&P500_Adj.csv",                  "%d.%m.%y"),
    "Dow":   (f"{EMPIRICAL_DIR}/Dow_Adj.csv",                     "%Y-%m-%d"),
    # synthetic price series generated by garch.data.synthetic
    "MonteCarlo": (f"{ARTIFICIAL_DIR}/monte_carlo.csv", "%Y-%m-%d"),
    "GARCH_sim":  (f"{ARTIFICIAL_DIR}/garch.csv",       "%Y-%m-%d"),
    "DCC_sim":    (f"{ARTIFICIAL_DIR}/dcc.csv",         "%Y-%m-%d"),
}


def risk_free_file() -> str:
    """
    Locate the Fed Funds total-return CSV.

    Auto-detects the latest ``Price History_*.csv`` in the empirical folder, so a
    freshly downloaded (re-dated) file is picked up without editing any code.
    """
    matches = sorted(glob.glob(f"{EMPIRICAL_DIR}/Price History_*.csv"))
    if not matches:
        raise FileNotFoundError(
            f"No 'Price History_*.csv' (Fed Funds risk-free) found in {EMPIRICAL_DIR}/"
        )
    return matches[-1]


# =============================================================================
# Solver configuration (riskfolio-lib / cvxpy)
# =============================================================================
# cvxpy's default C++ canonicalisation backend aborts (a hard SIGABRT) with
# numpy 2.x in this environment; the SciPy backend is correct and stable. We
# route every riskfolio solve through it. This is harmless on a healthy install
# and required on a broken one.
SOLVERS = ["CLARABEL"]
SOL_PARAMS = {"CLARABEL": {"canon_backend": "SCIPY"}}


# =============================================================================
# Backtest configuration
# =============================================================================

@dataclass(frozen=True)
class BacktestConfig:
    """Everything that defines a single backtest run."""

    dataset: str = "DCC_sim"
    train_window: int = 4 * 252          # ~4 years of trading days
    prediction_window: int = 1           # test/forecast horizon in days
    garch_p: int = 1
    garch_q: int = 1
    cov_methods: tuple[str, ...] = ("Historical", "GARCH", "DCC")
    models: tuple[str, ...] = ("MVP", "HRP", "ERC")
    log_weights: bool = True             # also dump per-window weights to weights.csv
    max_workers: int = 3

    @property
    def garch_tag(self) -> str:
        return "" if (self.garch_p, self.garch_q) == (1, 1) else f"_g{self.garch_p}-{self.garch_q}"

    @property
    def output_dir(self) -> str:
        return f"{RESULTS_DIR}/{self.dataset}/{self.train_window}_{self.prediction_window}{self.garch_tag}"
